--CREATE DATABASE LibreriaUTN;
--GO
--USE LibreriaUTN
--GO

--CREATE TABLE Cliente (
--	IDCliente INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
--	DNI INT UNIQUE NOT NULL,
--	Nombre NVARCHAR(50) NOT NULL,
--	Apellido NVARCHAR(50) NOT NULL,
--	Telefono INT,
--	Mail NVARCHAR(100) NOT NULL
--)
--GO

--CREATE TABLE Autor (
--	IDAutor INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	NombreAutor NVARCHAR(50) NOT NULL,
--	ApellidoAutor NVARCHAR(50) NOT NULL
--)
--GO

--CREATE TABLE GENERO (
--	IDGenero INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	NombreGenero NVARCHAR(50) NOT NULL
--)
--GO

--CREATE TABLE Editorial (
--	IDEditorial INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	NombreEditorial NVARCHAR(50) NOT NULL
--)
--GO

--CREATE TABLE Libro (
--	IDLibro INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	Titulo NVARCHAR(50) NOT NULL,
--	IDAutor INT NOT NULL FOREIGN KEY REFERENCES Autor(IDAutor),
--	IDGenero INT NOT NULL FOREIGN KEY REFERENCES Genero(IDGenero),
--	Descripcion NVARCHAR(200) NOT NULL,
--	CantidadDePaginas INT NOT NULL,
--	FechaDePublicacion DATETIME NOT NULL,
--	IDEditorial INT NOT NULL FOREIGN KEY REFERENCES Editorial(IDEditorial),
--	Precio MONEY NOT NULL
--)
--GO

--CREATE TABLE Compras (
--	IDCompra INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente(IDCliente),
--	FechaDeCompra DATETIME NOT NULL,
--	IDLibroComprado INT NOT NULL FOREIGN KEY REFERENCES Libro(IDLibro),
--	Importe MONEY NOT NULL,
--	MedioDePago NVARCHAR(50) NOT NULL
--)
--GO

--CREATE TABLE Devoluciones (
--	IDDevolucion INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
--	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente(IDCliente),
--	IDCompra INT NOT NULL FOREIGN KEY REFERENCES Compras(IDCompra),
--	FechaDevolucion DATETIME NOT NULL,
--	ImporteDevolucion MONEY NOT NULL,
--	IDLibroDevuelto INT FOREIGN KEY REFERENCES Libro(IDLibro)
--)
--GO